### PR TITLE
Create byler20150609.md

### PR DESCRIPTION
**Pull request by nell-byler**

### CODE REVIEW

**Comment by nell-byler** [comment]
I thought it might be a good idea to separate these into two different posts - what do you think?

**Comment by bmorris3** [comment]
As long as there's enough content to fill a single post, separating them is a great idea. :+1:

**Comment by bmorris3** [comment]
@nell-byler , it looks like the "Related Topics, suggested tags" section is left with the default. What keywords would you use for this Genius Effect post? Feel free to do a second PR.

**Comment by bmorris3** [comment]
@nell-byler – before this is closed for good, would you update the keywords/tags?

**Pull request merged**
